In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('website/data/ghg_emission_2020.csv')
df

,Local Authority Code,Region,Second Tier Authority,Local Authority,Calendar Year,Greenhouse gas,CO2_Agriculture,CO2_Commercial,CO2_Domestic,CO2_Industry,CO2_Public Sector,CO2_Transport,CO2_Grand Total
0,E06000001,North East,Hartlepool,Hartlepool,2020,CO2,2.251930,24.762401,129.593025,296.397313,12.781472,123.183476,588.969618
1,E06000002,North East,Middlesbrough,Middlesbrough,2020,CO2,1.128088,25.002619,186.449637,57.037806,40.305385,249.982780,559.906315
2,E06000003,North East,Redcar and Cleveland,Redcar and Cleveland,2020,CO2,5.289547,50.688876,201.822606,1219.022000,12.173020,181.970446,1670.966497
3,E06000004,North East,Stockton-on-Tees,Stockton-on-Tees,2020,CO2,11.470850,80.351948,269.953429,1734.808554,40.626593,294.939859,2458.435832
4,E06000005,North East,Darlington,Darlington,2020,CO2,6.885545,22.465810,161.741986,114.399399,18.202869,166.106173,489.801782
...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,E09000032,London,Wandsworth,Wandsworth,2020,CO2,0.280672,92.128017,380.498644,31.896690,85.104922,214.912893,804.821838
305,E09000033,London,Westminster,Westminster,2020,CO2,5.495394,605.120575,265.899693,110.963008,168.872382,261.687103,1418.038156
306,E06000060,South East,Buckinghamshire,Buckinghamshire,2020,CO2,49.034476,151.877022,858.092731,146.539006,83.641114,1141.223883,2430.408231
307,E06000061,East Midlands,Northamptonshire,North Northamptonshire,2020,CO2,24.288697,99.635281,479.569874,315.384993,28.624921,681.950525,1629.454290
308,E06000062,East Midlands,Northamptonshire,West Northamptonshire,2020,CO2,48.014031,170.653860,553.474642,197.975354,61.021906,1107.212117,2138.351909

In [14]:
df.columns

Index(['Local Authority Code', 'Region', 'Second Tier Authority',
       'Local Authority', 'Calendar Year', 'Greenhouse gas', 'CO2_Agriculture',
       'CO2_Commercial', 'CO2_Domestic', 'CO2_Industry', 'CO2_Public Sector',
       'CO2_Transport', 'CO2_Grand Total'],
      dtype='object')

In [16]:
top10_df = df.sort_values(by=['CO2_Grand Total'],ascending=False).head(10)
top10_df = top10_df.round(0)
top10_df = top10_df.rename({
    'CO2_Agriculture':'Agriculture',
    'CO2_Commercial':'Commercial',
    'CO2_Domestic' : 'Domestic',
    'CO2_Industry' : 'Industry',
    'CO2_Public Sector' : 'Public Sector',
    'CO2_Transport': 'Transport'
},axis=1)
top10_df

,Local Authority Code,Region,Second Tier Authority,Local Authority,Calendar Year,Greenhouse gas,Agriculture,Commercial,Domestic,Industry,Public Sector,Transport,CO2_Grand Total
12,E06000013,Yorkshire and the Humber,North Lincolnshire,North Lincolnshire,2020,CO2,26.0,40.0,252.0,5680.0,12.0,413.0,6423.0
260,E08000025,West Midlands,Birmingham,Birmingham,2020,CO2,4.0,336.0,1333.0,528.0,245.0,1275.0,3721.0
46,E06000050,North West,Cheshire,Cheshire West and Chester,2020,CO2,51.0,176.0,516.0,1832.0,68.0,758.0,3475.0
270,E08000035,Yorkshire and the Humber,Leeds,Leeds,2020,CO2,13.0,284.0,1050.0,492.0,177.0,1447.0,3473.0
72,E07000037,East Midlands,Derbyshire,High Peak,2020,CO2,12.0,23.0,144.0,2362.0,10.0,136.0,2686.0
3,E06000004,North East,Stockton-on-Tees,Stockton-on-Tees,2020,CO2,11.0,80.0,270.0,1735.0,41.0,295.0,2458.0
306,E06000060,South East,Buckinghamshire,Buckinghamshire,2020,CO2,49.0,152.0,858.0,147.0,84.0,1141.0,2430.0
10,E06000011,Yorkshire and the Humber,East Riding of Yorkshire,East Riding of Yorkshire,2020,CO2,128.0,120.0,563.0,815.0,55.0,692.0,2374.0
50,E06000054,South West,Wiltshire,Wiltshire,2020,CO2,129.0,137.0,680.0,282.0,102.0,1005.0,2335.0
48,E06000052,South West,Cornwall,Cornwall,2020,CO2,169.0,203.0,725.0,314.0,63.0,853.0,2331.0

In [17]:
top10_df.to_csv('ghg_website/data/top10_co2_emission.csv',index=False)

In [7]:
df.sort_values(by=['CO2_Grand Total'],ascending=True).head(10)

,Local Authority Code,Region,Second Tier Authority,Local Authority,Calendar Year,Greenhouse gas,CO2_Agriculture,CO2_Commercial,CO2_Domestic,CO2_Industry,CO2_Public Sector,CO2_Transport,CO2_Grand Total
49,E06000053,South West,Isles of Scilly,Isles of Scilly,2020,CO2,0.222925,1.222431,2.201895,0.235727,0.130925,2.476135,6.490038
153,E07000135,East Midlands,Leicestershire,Oadby and Wigston,2020,CO2,0.415261,9.203102,81.027444,24.937867,8.575296,44.248484,168.407455
110,E07000088,South East,Hampshire,Gosport,2020,CO2,0.302614,15.482536,90.653378,22.311723,12.908389,58.424525,200.083164
217,E07000223,South East,West Sussex,Adur,2020,CO2,1.727276,13.397367,78.207178,18.401389,6.855792,87.991444,206.580446
202,E07000208,South East,Surrey,Epsom and Ewell,2020,CO2,0.500769,12.887282,118.600550,4.223161,15.423372,66.240418,217.875551
197,E07000199,West Midlands,Staffordshire,Tamworth,2020,CO2,0.383475,14.599409,96.116885,35.409758,4.150316,71.479706,222.139550
84,E07000062,South East,East Sussex,Hastings,2020,CO2,0.487829,20.508532,113.810156,15.786635,12.980632,64.111540,227.685325
64,E07000029,North West,Cumbria,Copeland,2020,CO2,16.901677,11.385931,110.465237,14.293206,12.020197,64.167694,229.233943
96,E07000074,East of England,Essex,Maldon,2020,CO2,10.886592,10.482741,97.042390,49.781162,3.249861,75.486742,246.929488
97,E07000075,East of England,Essex,Rochford,2020,CO2,4.390163,15.750047,124.192098,18.481794,6.688503,92.264183,261.766789